name: Python application

on:
  push:
    branches: [ "master" ]
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          
      - name: create env
        run: |
          pip install virtualenv
          virtualenv env
          source env/bin/activate          
          pip install -r requirements.txt
          zappa update dev
          zappa update dev2
          
      - name: Hazlo
        run: |
          source $VIRTUALENV/bin/activate
          zappa invoke dev extraer.lambda1
          pytest test.py
